"""
This script defines the reward function for the nanoGPT alignment project.
The reward function is based on a simple heuristic.
"""

import sys


def calculate_reward(text: str) -> float:
    """
    Calculates a reward score for a given text based on a simple heuristic.

    The heuristic is to count the total number of occurrences of the letter 'e'.

    Args:
        text (str): The input text generated by the model.

    Returns:
        float: The calculated reward score.
    """
    # The rule is to count the total number of appearances of the letter 'e'.
    # We convert the text to lowercase to count both 'e' and 'E'.
    reward = float(text.strip().lower().count("e"))
    return reward


# Example usage and simple test cases
if __name__ == "__main__":
    test_text_1 = " This is a sample sentence to test the reward function."
    reward_1 = calculate_reward(test_text_1)
    print(f"Text: '{test_text_1}'")
    print(f"Reward (count of 'e'): {reward_1}")
    # Expected: sample (1), sentence (3), test (1), the (1), reward (1) = 7. Let's re-check: s-e-nt-e-nc-e (3), t-e-st (1), th-e (1), r-e-ward (1). Wait, sample has no 'e'. So 3+1+1+1=6. My manual count was wrong. Let's fix the comment.
    # Corrected count: sentence (3), test (1), the (1), reward (1) = 6.
    # Let's recount the first example: "This is a sample s**e**nt**e**nc**e** to t**e**st th**e** r**e**ward function." -> 6 'e's.
    # Let's recount the third example: "**E**l**e**phants ar**e** **e**xtr**e**m**e**ly **e**l**e**gant." -> 8 'e's.
    # The code is correct, my comments were slightly off. I will use the correct expected values in the final code.

    print("-" * 20)

    test_text_2 = "A quick brown fox jumps high."
    reward_2 = calculate_reward(test_text_2)
    print(f"Text: '{test_text_2}'")
    print(f"Reward (count of 'e'): {reward_2}")

    print("-" * 20)

    test_text_3 = "Elephants are extremely elegant."
    reward_3 = calculate_reward(test_text_3)
    print(f"Text: '{test_text_3}'")
    print(f"Reward (count of 'e'): {reward_3}")

    print("-" * 20)

    user_data = ""
    for line in sys.stdin:
        clean_line = line
        if clean_line:
            user_data += clean_line

    reward_user_data = calculate_reward(user_data)
    print(f"Text: '{user_data}'")
    print(f"Reward (count of 'e'): {reward_user_data}")
